site_name: Stakater App Agility Platform (SAAP)
docs_dir: content
site_url: https://docs.stakater.com/saap/
repo_url: https://github.com/stakater/saap-docs
edit_uri: blob/main/content/
use_directory_urls: false
strict: true
theme:
    name: material
    logo: assets/images/favicon.svg
    favicon: assets/images/favicon.svg
    custom_dir: custom_theme/
    palette:
        primary: white

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
    analytics:
        provider: google
        property: G-TTH1YYW5TX
    consent:
        title: Cookie consent
        actions:
            - accept
            - reject
            - manage
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.

nav:
    - About:
        - index.md
        - Enterprise Kubernetes: about/saap-vs-k8s.md
        - about/saap-features.md
        - about/saap-key-differentiators.md
        - Service Definition:
            - about/service-definition/overview.md
            - about/service-definition/account-management.md
            - about/service-definition/k8s-management.md
            - about/service-definition/logging.md
            - about/service-definition/monitoring.md
            - about/service-definition/networking.md
            - about/service-definition/storage.md
            - about/service-definition/platform.md
            - about/service-definition/security.md
            - about/service-definition/secrets-management.md
            - about/service-definition/artifacts-management.md
            - about/service-definition/cicd-pipelines.md
            - about/service-definition/service-mesh.md
            - about/service-definition/multitenancy.md
        - Responsibilities:
            - about/responsibilities/overview.md
            - about/responsibilities/incident-operations-management.md
            - about/responsibilities/change-management.md
            - about/responsibilities/identity-access-management.md
            - about/responsibilities/security-regulation-compliance.md
            - about/responsibilities/disaster-recovery.md
        - Cloud Providers:
            - about/cloud-providers/overview.md
            - about/cloud-providers/aws.md
            - about/cloud-providers/azure.md
            - about/cloud-providers/complior.md
            - about/cloud-providers/elastx.md
            - about/cloud-providers/gcp.md
            - about/cloud-providers/binero.md
            - about/cloud-providers/upcloud.md
            - about/cloud-providers/exoscale.md
            - about/cloud-providers/safespring.md
        - about/update-lifecycle.md
        - about/onboarding.md
    - For Administrators:
        - Plan your envionment:
            - for-administrators/plan-your-environment/sizing.md
        - Provision your cluster:
            - for-administrators/provision-your-cluster.md
        - Secure your cluster:
            - for-administrators/secure-your-cluster/user-access.md
            - for-administrators/secure-your-cluster/secure-routes.md
        - Onboarding:
            - Day 1:
                - for-administrators/onboarding/day1/bootstrap-gitops.md
                - for-administrators/onboarding/day1/add-cluster.md
                - for-administrators/onboarding/day1/add-template.md
            - Day 2:
                - for-administrators/onboarding/day2/add-quota.md
                - for-administrators/onboarding/day2/add-tenant.md
                - for-administrators/onboarding/day2/add-template.md
        - Manage Network:
            - for-administrators/networking/custom-domains.md
            - for-administrators/networking/external-dns.md
        - Manage Storage:
            - for-administrators/storage/volume-expansion.md
        - for-administrators/capacity-management.md
        - for-administrators/disaster-recovery.md
        - for-administrators/registry-cicd.md
        - for-administrators/use-of-credentials.md
        - Security Best Practices:
            - for-administrators/security/overview.md
            - for-administrators/security/identity-verification-access-control.md
            - for-administrators/security/pod-security.md
            - for-administrators/security/runtime-security.md
            - for-administrators/security/supply-chain-security.md
            - for-administrators/security/data-encryption-secret-management.md
            - for-administrators/security/network-security.md
            - for-administrators/security/logging-auditing.md
            - for-administrators/security/multi-tenancy-security.md
            - for-administrators/security/host-security.md
        - Cluster Lifecycle:
            - for-administrators/cluster-lifecycle/hibernate-your-cluster.md
            - for-administrators/cluster-lifecycle/add-node-to-your-cluster.md
            - for-administrators/cluster-lifecycle/autoscale-your-cluster.md
            - for-administrators/cluster-lifecycle/upgrade-your-cluster.md
            - for-administrators/cluster-lifecycle/terminate-your-cluster.md
        - Help:
            - for-administrators/help/troubleshooting.md
            - for-administrators/help/faq.md
    - For Delivery Engineers:
        - for-delivery-engineers/overview.md
        - GitOps:
            - for-delivery-engineers/gitops/introduction.md
            - for-delivery-engineers/gitops/structure.md
            - for-delivery-engineers/gitops/creating-gitops-structure.md
            - for-delivery-engineers/gitops/gitops-argocd-secrets.md
            - for-delivery-engineers/gitops/application-onboarding.md
            - for-delivery-engineers/gitops/environments.md
            - for-delivery-engineers/gitops/github.md
            - for-delivery-engineers/gitops/gitlab.md
            - for-delivery-engineers/gitops/faq.md
        - Continous Integration:
            - for-delivery-engineers/ci-pipelines/secrets.md
            - Tekton:
                - for-delivery-engineers/ci-pipelines/tekton/intro.md
                - for-delivery-engineers/ci-pipelines/tekton/bot-account.md
            - GitHub Actions:
                - for-delivery-engineers/ci-pipelines/github-actions/intro.md
        - Continous Delivery:
            - ArgoCD:
                - for-delivery-engineers/cd-pipelines/argocd/intro.md
    - For Developers:
        - Overview:
            - for-developers/overview.md
            - for-developers/develop-your-application.md
            - for-developers/access-your-cluster.md
            - for-developers/explore-argocd-vault-nexus.md
            - for-developers/plan-your-deployment.md
            - for-developers/requirements-for-next-section.md
            - for-developers/help.md
        - Deploy your App:
            - for-developers/containerize-the-application.md
            - for-developers/package-the-application.md
            - for-developers/deploy-the-application.md
        - Networking:
            - for-developers/expose-your-application.md
        - Persistence:
            - for-developers/persist-your-application.md
            - for-developers/backup-your-application.md
        - Scaling:
            - for-developers/scale-your-application.md
        - Logging & Monitoring:
            - for-developers/enable-metrics-for-your-application.md
            - for-developers/enable-logging-for-your-application.md
            - for-developers/enable-alerts-for-your-application.md
            - for-developers/add-grafana-dashboard-for-your-application.md
        - Onboarding:
            - for-developers/onboarding/tenant-onboarding.md
            - for-developers/onboarding/environment-onboarding.md
            - for-developers/onboarding/developer-training.md
            - for-developers/onboarding/secrets.md
        - Local Development:
            - for-developers/local-development/inner-loop.md
            - for-developers/local-development/inner-vs-outer-loop.md
            - for-developers/local-development/local-development-workflow.md
            - for-developers/local-development/tilt/step-by-step-guide.md
    - For CISOs:
        - for-cisos/overview.md
        - for-cisos/policies/policies.md
        - Red Hat Advanced Cluster Security (RHACS):
            - for-cisos/rhacs/introduction.md
            - for-cisos/rhacs/accessing-rhacs.md
            - for-cisos/rhacs/permissions.md
        - Authentication and Authorization:
            - for-cisos/authentication-authorization/google-idp.md
            - for-cisos/authentication-authorization/azure-idp.md
            - for-cisos/authentication-authorization/keycloak-idp.md
            - for-cisos/authentication-authorization/saml-idp.md
            - for-cisos/authentication-authorization/saap-authorization-roles.md
            - for-cisos/authentication-authorization/curated-list-operators.md
        - Backup and Restore:
            - for-cisos/backup-restore/introduction.md
            - for-cisos/backup-restore/velero-cli.md
            - for-cisos/backup-restore/backup-restore.md
            - for-cisos/backup-restore/troubleshooting.md
            - for-cisos/backup-restore/cleanup.md
            - for-cisos/backup-restore/stateful-app-example.md
            - for-cisos/backup-restore/restore-with-gitops.md
            - for-cisos/backup-restore/limitations.md
        - Data Protection:
            - for-cisos/data-protection/gdpr.md
            - for-cisos/data-protection/rhacm-data-lifecycle.md
            - for-cisos/data-protection/rhacm-data-collection.md
            - for-cisos/data-protection/rhacm-data-storage.md
    - For Partners:
        - for-partners/overview.md
    - Managed Addons:
        - managed-addons/overview.md
        - Nexus:
            - managed-addons/nexus/overview.md
            - managed-addons/nexus/accessing-repository.md
            - managed-addons/nexus/permissions.md
            - managed-addons/nexus/routes.md
            - managed-addons/nexus/maven-setup.md
            - managed-addons/nexus/grant-nexus-admin-keycloak.md
            - managed-addons/nexus/faq.md
        - Vault:
            - managed-addons/vault/overview.md
        - ArgoCD:
            - managed-addons/argocd/overview.md
        - Cert Manager:
            - managed-addons/cert-manager/overview.md
        - External Secrets Operator:
            - managed-addons/external-secrets-operator/overview.md
        - Forecastle:
            - managed-addons/forecastle/overview.md
        - Ingress Monitor Controller:
            - managed-addons/imc/overview.md
        - Konfigurator:
            - managed-addons/konfigurator/overview.md
        - Logging:
            - managed-addons/logging-stack/overview.md
            - managed-addons/logging-stack/kibana-view-logs.md
        - Monitoring:
            - managed-addons/monitoring-stack/overview.md
            - managed-addons/monitoring-stack/stack.md
            - managed-addons/monitoring-stack/app-uptime.md
            - managed-addons/monitoring-stack/app-alerts.md
            - managed-addons/monitoring-stack/grafana-dashboard.md
            - managed-addons/monitoring-stack/downtime-notifications-uptimerobot.md
            - managed-addons/monitoring-stack/log-alerts.md
            - managed-addons/monitoring-stack/predefined-prometheusrules.md
            - managed-addons/monitoring-stack/workload-application-alerts.md
        - Multi Tenant Operator:
            - managed-addons/mto/overview.md
        - Reloader:
            - managed-addons/reloader/overview.md
        - SonarQube:
            - managed-addons/sonarqube/overview.md
            - managed-addons/sonarqube/sonarqube-upgrade.md
        - Tekton:
            - managed-addons/tekton/introduction.md
            - managed-addons/tekton/cluster-tasks.md
            - managed-addons/tekton/openshift-pipelines/openshift-pipelines.md
            - managed-addons/tekton/openshift-pipelines/deploying-cicd-pipeline.md
            - managed-addons/tekton/openshift-pipelines/deploying-delivery-pipeline.md
        - Tronador:
            - managed-addons/tronador/overview.md
        - Velero:
            - managed-addons/velero/overview.md
    - Legal Documents:
        - legal-documents/gtc.md
        - legal-documents/sla.md
        - legal-documents/agreement.md
        - legal-documents/dpa.md
        - legal-documents/nda.md
        - legal-documents/pp.md
    - Help:
        - help/overview.md
        - help/support/support.md
        - Kubernetes Concepts:
            - help/k8s-concepts/overview.md
            - help/k8s-concepts/storage-basics.md
            - help/k8s-concepts/container-anatomy.md
            - help/k8s-concepts/cloud-native-app.md
            - help/k8s-concepts/helm.md
            - help/k8s-concepts/high-availability.md
        - FAQs:
            - help/faqs/product.md
            - help/faqs/purchasing.md
            - help/faqs/customization.md
            - help/faqs/developers.md
            - help/faqs/operations.md

plugins:
    - search
    - mermaid2
